### ISSUE TITLE
Redraw requests threading problem

### ISSUE THREAD

**Issue by haansn08** [Manuel57/MI-C_Monopoly#20]
On some devices redraw requests may fail if called from some other thread.
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-797
    Process: com.se.monopoly, PID: 5694
    android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
        at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:7665)
        at android.view.ViewRootImpl.invalidateChildInParent(ViewRootImpl.java:1156)
        at android.view.ViewGroup.invalidateChild(ViewGroup.java:5033)
        at android.view.View.invalidateInternal(View.java:13023)
        at android.view.View.invalidate(View.java:12987)
        at android.view.View.invalidate(View.java:12971)
        at com.se.monopoly.-$$Lambda$wRyNd2f_SxzpngWd-qWSEZ3ID54.onRedrawRequest(lambda)
        at com.se.monopoly.domain.Player.redraw(Player.java:101)
        at com.se.monopoly.controller.GameController.moveOneField(GameController.java:60)
        at com.se.monopoly.domain.Player$1.run(Player.java:64)
        at java.lang.Thread.run(Thread.java:818)
```

**Comment by haansn08** [comment]
Fixed by e197789bcab14f2407bbac97374b4d98c4296c08
