### ISSUE TITLE
[Network] Client crash on game start

### ISSUE THREAD

**Issue by haansn08** [Manuel57/MI-C_Monopoly#31]
Sometimes client crashes when host attempts to start the game.
Host does not crash.

## Cause
This is caused by the client not receiving the number of players in the game.
`gameController.getNumberOfPlayers()` returns 0.

**Comment by haansn08** [comment]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.se.monopoly, PID: 7039
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.se.monopoly/com.se.monopoly.activities.GameActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class com.se.monopoly.views.GameboardView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3150)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260)
        at android.app.ActivityThread.access$1000(ActivityThread.java:218)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6934)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
     Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class com.se.monopoly.views.GameboardView
        at android.view.LayoutInflater.createView(LayoutInflater.java:640)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:366)
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:450)
        at android.app.Activity.setContentView(Activity.java:2400)
        at com.se.monopoly.activities.GameActivity.onCreate(GameActivity.java:27)
        at android.app.Activity.performCreate(Activity.java:6609)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3103)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:218) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.app.ActivityThread.main(ActivityThread.java:6934) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:614)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:511) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:366) 
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:450) 
        at android.app.Activity.setContentView(Activity.java:2400) 
        at com.se.monopoly.activities.GameActivity.onCreate(GameActivity.java:27) 
        at android.app.Activity.performCreate(Activity.java:6609) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3103) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:218) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.app.ActivityThread.main(ActivityThread.java:6934) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
     Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
        at com.se.monopoly.controller.GameController.setPlayers(GameController.java:99)
        at com.se.monopoly.views.GameboardView.<init>(GameboardView.java:74)
        at java.lang.reflect.Constructor.newInstance(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:614) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:511) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:366) 
        at com.android.internal.policy.impl.PhoneWindow.setContentView(PhoneWindow.java:450) 
        at android.app.Activity.setContentView(Activity.java:2400) 
        at com.se.monopoly.activities.GameActivity.onCreate(GameActivity.java:27) 
        at android.app.Activity.performCreate(Activity.java:6609) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3103) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3260) 
        at android.app.ActivityThread.access$1000(ActivityThread.java:218) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1734) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:145) 
        at android.app.ActivityThread.main(ActivityThread.java:6934) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 
```

**Comment by Manuel57** [comment]
You have to wait until client is ready before starting the game
